from collections import namedtuple

Kanamoji = namedtuple('Kanamoji', ['kind', 'hirigana', 'katakana', 'romaji'])

KANAMOJI = [
 Kanamoji(kind='dakuon', hirigana='ご', katakana='ゴ', romaji='go'),
 Kanamoji(kind='seion', hirigana='ぬ', katakana='ヌ', romaji='nu'),
 Kanamoji(kind='dakuon', hirigana='ぽ', katakana='ポ', romaji='po'),
 Kanamoji(kind='seion', hirigana='ん', katakana='ン', romaji='n'),
 Kanamoji(kind='seion', hirigana='え', katakana='エ', romaji='e'),
 Kanamoji(kind='seion', hirigana='な', katakana='ナ', romaji='na'),
 Kanamoji(kind='seion', hirigana='む', katakana='ム', romaji='mu'),
 Kanamoji(kind='seion', hirigana='ち', katakana='チ', romaji='chi'),
 Kanamoji(kind='seion', hirigana='て', katakana='テ', romaji='te'),
 Kanamoji(kind='dakuon', hirigana='ば', katakana='バ', romaji='ba'),
 Kanamoji(kind='seion', hirigana='を', katakana='ヲ', romaji='o '),
 Kanamoji(kind='seion', hirigana='あ', katakana='ア', romaji='a'),
 Kanamoji(kind='seion', hirigana='こ', katakana='コ', romaji='ko'),
 Kanamoji(kind='seion', hirigana='う', katakana='ウ', romaji='u'),
 Kanamoji(kind='seion', hirigana='や', katakana='ヤ', romaji='ya'),
 Kanamoji(kind='dakuon', hirigana='ぜ', katakana='ゼ', romaji='ze'),
 Kanamoji(kind='seion', hirigana='つ', katakana='ツ', romaji='tsu'),
 Kanamoji(kind='dakuon', hirigana='だ', katakana='ダ', romaji='da'),
 Kanamoji(kind='dakuon', hirigana='で', katakana='デ', romaji='de'),
 Kanamoji(kind='seion', hirigana='き', katakana='キ', romaji='ki'),
 Kanamoji(kind='seion', hirigana='ら', katakana='ラ', romaji='ra'),
 Kanamoji(kind='seion', hirigana='ろ', katakana='ロ', romaji='ro'),
 Kanamoji(kind='seion', hirigana='お', katakana='オ', romaji='o'),
 Kanamoji(kind='dakuon', hirigana='ざ', katakana='ザ', romaji='za'),
 Kanamoji(kind='dakuon', hirigana='ぐ', katakana='グ', romaji='gu'),
 Kanamoji(kind='dakuon', hirigana='ぷ', katakana='プ', romaji='pu'),
 Kanamoji(kind='seion', hirigana='そ', katakana='ソ', romaji='so'),
 Kanamoji(kind='seion', hirigana='せ', katakana='セ', romaji='se'),
 Kanamoji(kind='seion', hirigana='る', katakana='ル', romaji='ru'),
 Kanamoji(kind='dakuon', hirigana='が', katakana='ガ', romaji='ga'),
 Kanamoji(kind='dakuon', hirigana='げ', katakana='ゲ', romaji='ge'),
 Kanamoji(kind='dakuon', hirigana='ぴ', katakana='ピ', romaji='pi'),
 Kanamoji(kind='seion', hirigana='ふ', katakana='フ', romaji='fu'),
 Kanamoji(kind='dakuon', hirigana='づ', katakana='ヅ', romaji='zu '),
 Kanamoji(kind='dakuon', hirigana='ぼ', katakana='ボ', romaji='bo'),
 Kanamoji(kind='dakuon', hirigana='ず', katakana='ズ', romaji='zu'),
 Kanamoji(kind='seion', hirigana='さ', katakana='サ', romaji='sa'),
 Kanamoji(kind='seion', hirigana='た', katakana='タ', romaji='ta'),
 Kanamoji(kind='dakuon', hirigana='ぱ', katakana='パ', romaji='pa'),
 Kanamoji(kind='seion', hirigana='わ', katakana='ワ', romaji='wa'),
 Kanamoji(kind='seion', hirigana='ひ', katakana='ヒ', romaji='hi'),
 Kanamoji(kind='dakuon', hirigana='び', katakana='ビ', romaji='bi'),
 Kanamoji(kind='seion', hirigana='と', katakana='ト', romaji='to'),
 Kanamoji(kind='seion', hirigana='か', katakana='カ', romaji='ka'),
 Kanamoji(kind='dakuon', hirigana='ぎ', katakana='ギ', romaji='gi'),
 Kanamoji(kind='seion', hirigana='り', katakana='リ', romaji='ri'),
 Kanamoji(kind='dakuon', hirigana='ぺ', katakana='ペ', romaji='pe'),
 Kanamoji(kind='seion', hirigana='ほ', katakana='ホ', romaji='ho'),
 Kanamoji(kind='seion', hirigana='み', katakana='ミ', romaji='mi'),
 Kanamoji(kind='seion', hirigana='し', katakana='シ', romaji='shi'),
 Kanamoji(kind='seion', hirigana='よ', katakana='ヨ', romaji='yo'),
 Kanamoji(kind='dakuon', hirigana='べ', katakana='ベ', romaji='be'),
 Kanamoji(kind='seion', hirigana='ね', katakana='ネ', romaji='ne'),
 Kanamoji(kind='dakuon', hirigana='ぞ', katakana='ゾ', romaji='zo'),
 Kanamoji(kind='dakuon', hirigana='ど', katakana='ド', romaji='do'),
 Kanamoji(kind='seion', hirigana='ゆ', katakana='ユ', romaji='yu'),
 Kanamoji(kind='seion', hirigana='ま', katakana='マ', romaji='ma'),
 Kanamoji(kind='seion', hirigana='す', katakana='ス', romaji='su'),
 Kanamoji(kind='seion', hirigana='れ', katakana='レ', romaji='re'),
 Kanamoji(kind='dakuon', hirigana='ぶ', katakana='ブ', romaji='bu'),
 Kanamoji(kind='seion', hirigana='も', katakana='モ', romaji='mo'),
 Kanamoji(kind='seion', hirigana='く', katakana='ク', romaji='ku'),
 Kanamoji(kind='seion', hirigana='の', katakana='ノ', romaji='no'),
 Kanamoji(kind='seion', hirigana='へ', katakana='ヘ', romaji='he'),
 Kanamoji(kind='dakuon', hirigana='ぢ', katakana='ヂ', romaji='ji '),
 Kanamoji(kind='seion', hirigana='は', katakana='ハ', romaji='ha'),
 Kanamoji(kind='seion', hirigana='め', katakana='メ', romaji='me'),
 Kanamoji(kind='seion', hirigana='い', katakana='イ', romaji='i'),
 Kanamoji(kind='seion', hirigana='に', katakana='ニ', romaji='ni'),
 Kanamoji(kind='seion', hirigana='け', katakana='ケ', romaji='ke')
]
